CREATE EXTERNAL TABLE [ONS].[Fact_CRM_Opportunity_Consumption] (
    [Source_System_Identifier] smallINT NULL,
    [Logical_Deletion_Indicator] VARCHAR (1) NULL,
    [Source_System_Update_Timestamp] DATETIME NULL,
    [Insert_GMT_Timestamp] DATETIME NULL,
    [Load_Job_Number] DECIMAL (15) NULL,
    [Source_System_Extract_GMT_Timestamp] DATETIME NULL,
    [CRM_Opportunity_Actual_Close_Date] DATE NULL,
    [CRM_Opportunity_Reference_Code] NVARCHAR (100) NULL,
    [CRM_Opportunity_Won_Date] DATE NULL,
    [CRM_Opportunity_Budget_Local_Amount] DECIMAL (38, 4) NULL,
    [CRM_Opportunity_Budget_USD_Amount] DECIMAL (38, 4) NULL,
    [CRM_Opportunity_Source_Campaign_Unique_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_Source_Campaign_Entity_Type_Name] NVARCHAR (128) NULL,
    [CRM_Opportunity_Created_By_Unique_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_Created_By_Entity_Type_Name] NVARCHAR (128) NULL,
    [CRM_Opportunity_Create_Date] DATE NULL,
    [CRM_Opportunity_Created_By_Delegate_Unique_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_Created_By_Delegate_Entity_Type_Name] NVARCHAR (128) NULL,
    [CRM_Opportunity_Potential_Customer_Unique_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_Potential_Customer_Entity_Type_Name] NVARCHAR (128) NULL,
    [CRM_Opportunity_Description] NVARCHAR (3999) NULL,
    [CRM_Opportunity_Close_Date] DATE NULL,
    [CRM_Opportunity_Total_Opportunity_Value_Local_Amount] DECIMAL (38, 4) NULL,
    [CRM_Opportunity_Total_Opportunity_Value_USD_Amount] DECIMAL (38, 4) NULL,
    [CRM_Opportunity_Currency_Exchange_Rate] DECIMAL (38, 10) NULL,
    [CRM_Opportunity_Add_Or_Remove_Product_Code] BIT NULL,
    [CRM_Opportunity_Add_Product_Code] BIT NULL,
    [CRM_Opportunity_Closed_As_Won_Lost_Code] INT NULL,
    [CRM_Opportunity_Closed_Won_Code] INT NULL,
    [CRM_Opportunity_Certificate_of_Installation_Date] DATE NULL,
    [CRM_Opportunity_Complete_Won_Lost_Analysis_Code] BIT NULL,
    [CRM_Opportunity_Confidential_Code] BIT NULL,
    [CRM_Opportunity_Contract_Approved_Date] DATE NULL,
    [CRM_Opportunity_Create_Solution_Opportunity_Approval_Review_Code] BIT NULL,
    [CRM_Opportunity_Create_Solution_Opportunity_Approval_Review_Lite_Code] BIT NULL,
    [CRM_Opportunity_Submit_Customer_Support_Information_Form_Code] BIT NULL,
    [CRM_Opportunity_Customer_Contact_First_Name] NVARCHAR (255) NULL,
    [CRM_Opportunity_Customer_Contact_Last_Name] NVARCHAR (255) NULL,
    [CRM_Opportunity_Customer_Email_Address_Text] NVARCHAR (80) NULL,
    [CRM_Opportunity_Customer_Engagement_Code] INT NULL,
    [CRM_Opportunity_Customer_Number] NVARCHAR (50) NULL,
    [CRM_Opportunity_Customer_Name] NVARCHAR (120) NULL,
    [CRM_Opportunity_Customer_Payment_Communicated_Code] BIT NULL,
    [CRM_Opportunity_Customer_Telephone_Number] NVARCHAR (100) NULL,
    [CRM_Opportunity_Dated_Currency_Exchange_Rate] DECIMAL (38, 6) NULL,
    [CRM_Opportunity_Won_Lost_Date] DATE NULL,
    [CRM_Opportunity_Deal_Registration_Id] NVARCHAR (100) NULL,
    [CRM_Opportunity_Deal_Registration_Status_Code] INT NULL,
    [CRM_Opportunity_Delivery_Date] DATE NULL,
    [CRM_Opportunity_Detailed_Won_Lost_Reason_Code] INT NULL,
    [CRM_Opportunity_Disable_Auto_Synchronization_Code] BIT NULL,
    [CRM_Opportunity_Distributor_On_Behalf_Of_Reseller_Code] BIT NULL,
    [CRM_Opportunity_Contract_Exist_Code] BIT NULL,
    [CRM_Opportunity_Delivery_Acceptance_Certificate_Of_Acceptance_Received_Date] DATE NULL,
    [CRM_Opportunity_Duplicate_Group_Unique_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_Duplicate_Group_Entity_Type_Name] NVARCHAR (128) NULL,
    [CRM_Opportunity_Expected_Renewal_Date] DATE NULL,
    [CRM_Opportunity_Finance_Method_Code] INT NULL,
    [CRM_Opportunity_Financing_information_Unique_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_Financing_Information_Entity_Type_Name] NVARCHAR (128) NULL,
    [CRM_Opportunity_Forecast_Category_Code] INT NULL,
    [CRM_Opportunity_Fulfillment_Code] INT NULL,
    [CRM_Opportunity_Funding_Status_Code] INT NULL,
    [CRM_Opportunity_Global_Business_Development_Manager_Unique_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_Global_Business_Development_Manager_Entity_Type_Name] NVARCHAR (128) NULL,
    [CRM_Opportunity_Begin_Won_Lost_Analysis_Code] BIT NULL,
    [CRM_Opportunity_Add_Deployment_Schedule_Code] BIT NULL,
    [CRM_Opportunity_Installation_Completed_Date_Entered_Code] BIT NULL,
    [CRM_Opportunity_Installation_Management_Coordinate_Operator_Training_Code] BIT NULL,
    [CRM_Opportunity_Activity_Logged_Code] BIT NULL,
    [CRM_Opportunity_Log_Additional_Activities_Code] BIT NULL,
    [CRM_Opportunity_Opportunity_Assessment_Approval_Code] BIT NULL,
    [CRM_Opportunity_Obtain_Approval_From_Sales_Operations_Finance_Services_Manager_Code] BIT NULL,
    [CRM_Opportunity_Send_Signed_Contract_or_Purchase_Order_Code] BIT NULL,
    [CRM_Opportunity_Synchronized_with_Deal_Analysis_Response_Tool_Code] BIT NULL,
    [CRM_Opportunity_Updated_Primary_Incumbent_and_Winning_Competitor_Code] BIT NULL,
    [CRM_Opportunity_Updated_Estimated_Close_Date_Code] BIT NULL,
    [CRM_Opportunity_Updated_Estimated_Close_Date_1_Code] BIT NULL,
    [CRM_Opportunity_Updated_Products_Code] BIT NULL,
    [CRM_Opportunity_Updated_Products_1_Code] BIT NULL,
    [CRM_Opportunity_Updated_Sales_Team_Code] BIT NULL,
    [CRM_Opportunity_HIPAA_Compliance_Required_Code] BIT NULL,
    [CRM_Opportunity_HP_Financial_Services_Engaged_Code] BIT NULL,
    [CRM_Opportunity_HP_Financial_Services_Engagement_Type_Code] INT NULL,
    [CRM_Opportunity_Where_Can_We_Improve_Description] NVARCHAR (3999) NULL,
    [CRM_Opportunity_Installation_Date] DATE NULL,
    [CRM_Opportunity_Installation_Comments_Description] NVARCHAR (3999) NULL,
    [CRM_Opportunity_Installation_Stage_Code] INT NULL,
    [CRM_Opportunity_Install_Management_Name] NVARCHAR (100) NULL,
    [CRM_Opportunity_Invoice_Date] DATE NULL,
    [CRM_Opportunity_Invoice_Number] NVARCHAR (50) NULL,
    [CRM_Opportunity_Order_Exist_Code] BIT NULL,
    [CRM_Opportunity_Order_Confirmed_Code] BIT NULL,
    [CRM_Opportunity_Training_Not_Needed_Code] BIT NULL,
    [CRM_Opportunity_Last_Stage_Change_Date] DATE NULL,
    [CRM_Opportunity_Latest_Approval_Request_Unique_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_Latest_Approval_Request_Entity_Type_Name] NVARCHAR (128) NULL,
    [CRM_Opportunity_Likelihood_Will_Revenue_Recognize_Code] INT NULL,
    [CRM_Opportunity_Managed_By_Code] INT NULL,
    [CRM_Opportunity_Services_Deal_Type_Code] INT NULL,
    [CRM_Opportunity_Multiple_Country_Code] BIT NULL,
    [CRM_Opportunity_Multiple_Country_Type_Code] INT NULL,
    [CRM_Opportunity_Operator_Training_Date] DATE NULL,
    [CRM_Opportunity_Opportunity_Group_Name] NVARCHAR (100) NULL,
    [CRM_Opportunity_Opportunity_Id] NVARCHAR (100) NULL,
    [CRM_Opportunity_Opportunity_Owner_Name] NVARCHAR (1300) NULL,
    [CRM_Opportunity_Ordering_Contact_Unique_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_Ordering_Contact_Entity_Type_Name] NVARCHAR (128) NULL,
    [CRM_Opportunity_Order_Status_Code] INT NULL,
    [CRM_Opportunity_HP_Owner_Unique_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_HP_Owner_Entity_Type_Name] NVARCHAR (128) NULL,
    [CRM_Opportunity_Driving_Opportunity_Unique_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_Driving_Opportunity_Entity_Type_Name] NVARCHAR (128) NULL,
    [CRM_Opportunity_Payment_Terms_Code] INT NULL,
    [CRM_Opportunity_Pipeline_Exclusion_Code] INT NULL,
    [CRM_Opportunity_Portal_Keep_Opportunity_Code] BIT NULL,
    [CRM_Opportunity_Send_Notification_Email_Code] BIT NULL,
    [CRM_Opportunity_Premier_Type_Code] INT NULL,
    [CRM_Opportunity_Pre_Press_Training_Date] DATE NULL,
    [CRM_Opportunity_Primary_Campaign_Unique_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_Primary_Campaign_Entity_Type_Name] NVARCHAR (128) NULL,
    [CRM_Opportunity_Primary_Partner_Unique_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_Primary_Partner_Entity_Type_Name] NVARCHAR (128) NULL,
    [CRM_Opportunity_Primary_Competitor_Unique_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_Primary_Competitor_Entity_Type_Name] NVARCHAR (128) NULL,
    [CRM_Opportunity_Prior_Sales_Stage_Name] NVARCHAR (255) NULL,
    [CRM_Opportunity_Product_Condition_Code] INT NULL,
    [CRM_Opportunity_Projected_Group_Value_Local_Amount] DECIMAL (38, 2) NULL,
    [CRM_Opportunity_Projected_Group_Value_USD_Amount] DECIMAL (38, 2) NULL,
    [CRM_Opportunity_Quote_Id_Synchronized_To_Name] NVARCHAR (2000) NULL,
    [CRM_Opportunity_Quote_Version_Synchronized_To_Name] NVARCHAR (100) NULL,
    [CRM_Opportunity_Renewal_Type_Code] INT NULL,
    [CRM_Opportunity_Requested_Quote_Code] BIT NULL,
    [CRM_Opportunity_Reseller_Account_Name] NVARCHAR (1300) NULL,
    [CRM_Opportunity_Reseller_Name_Unique_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_Reseller_Name_Entity_Type_Name] NVARCHAR (128) NULL,
    [CRM_Opportunity_Reseller_Unique_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_Reseller_Entity_Type_Name] NVARCHAR (128) NULL,
    [CRM_Opportunity_Revenue_Recognition_Date] DATE NULL,
    [CRM_Opportunity_Risk_Indicator_Code] INT NULL,
    [CRM_Opportunity_Route_To_Market_Code] INT NULL,
    [CRM_Opportunity_Automatic_Synchronization_Code] BIT NULL,
    [CRM_Opportunity_Serial_Number_Description] NVARCHAR (50) NULL,
    [CRM_Opportunity_Opportunity_SalesForce_com_Id] NVARCHAR (100) NULL,
    [CRM_Opportunity_Site_Survey_Date] DATE NULL,
    [CRM_Opportunity_Site_Survey_Status_Code] INT NULL,
    [CRM_Opportunity_Sales_Stage_Code] INT NULL,
    [CRM_Opportunity_Trade_Agreements_Act_Code] BIT NULL,
    [CRM_Opportunity_Tax_Id] NVARCHAR (100) NULL,
    [CRM_Opportunity_Tier_1_Opportunity_Value_Local_Amount] DECIMAL (38, 4) NULL,
    [CRM_Opportunity_Tier_1_Opportunity_Value_USD_Amount] DECIMAL (38, 4) NULL,
    [CRM_Opportunity_Tier_2_Opportunity_Value_Local_Amount] DECIMAL (38, 4) NULL,
    [CRM_Opportunity_Tier_2_Opportunity_Value_USD_Amount] DECIMAL (38, 4) NULL,
    [CRM_Opportunity_Total_Contract_Length_In_Months_Number] INT NULL,
    [CRM_Opportunity_Total_Opportunity_Country_Value_Local_Amount] DECIMAL (38, 2) NULL,
    [CRM_Opportunity_Total_Opportunity_Country_Value_USD_Amount] DECIMAL (38, 2) NULL,
    [CRM_Opportunity_Total_Opportunity_Group_Value_Local_Amount] DECIMAL (38, 2) NULL,
    [CRM_Opportunity_Total_Opportunity_Group_Value_USD_Amount] DECIMAL (38, 2) NULL,
    [CRM_Opportunity_Type_Code] INT NULL,
    [CRM_Opportunity_Unassigned_Opportunity_Code] BIT NULL,
    [CRM_Opportunity_What_Went_Well_Description] NVARCHAR (3999) NULL,
    [CRM_Opportunity_Additional_Comments_Text] NVARCHAR (3999) NULL,
    [CRM_Opportunity_World_Region_Unique_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_World_Region_Entity_Type_Name] NVARCHAR (128) NULL,
    [CRM_Opportunity_Unique_Id] VARCHAR (36) NOT NULL,
    [CRM_Opportunity_Identify_Competitors_Code] BIT NULL,
    [CRM_Opportunity_Identify_Customer_Contact_Code] BIT NULL,
    [CRM_Opportunity_Modified_By_Unique_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_Modified_By_Entity_Type_Name] NVARCHAR (128) NULL,
    [CRM_Opportunity_Last_Modified_Date] DATETIME NULL,
    [CRM_Opportunity_Partner_Unique_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_Partner_Entity_Type_Name] NVARCHAR (128) NULL,
    [CRM_Opportunity_Partner_Contact_Unique_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_Partner_Contact_Entity_Type_Name] NVARCHAR (128) NULL,
    [CRM_Opportunity_Name] NVARCHAR (300) NULL,
    [CRM_Opportunity_Originating_Lead_Unique_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_Originating_Lead_Entity_Type_Name] NVARCHAR (128) NULL,
    [CRM_Opportunity_Owner_Unique_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_Owner_Entity_Type_Name] NVARCHAR (128) NULL,
    [CRM_Opportunity_Owning_Business_Unit_Unique_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_Owning_Business_Unit_Entity_Type_Name] NVARCHAR (128) NULL,
    [CRM_Opportunity_Parent_Account_Unique_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_Parent_Account_Entity_Type_Name] NVARCHAR (128) NULL,
    [CRM_Opportunity_Parent_Contact_Unique_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_Parent_Contact_Entity_Type_Name] NVARCHAR (128) NULL,
    [CRM_Opportunity_Process_Unique_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_Synchronization_Database_Create_Timestamp] DATETIME NULL,
    [CRM_Opportunity_Synchronization_Database_Last_Modified_Timestamp] DATETIME NULL,
    [CRM_Opportunity_Status_Code] INT NULL,
    [CRM_Opportunity_Currency_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_Currency_Entity_Type_Name] NVARCHAR (128) NULL,
    [CRM_Opportunity_Add_Or_Remove_Product_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Add_Product_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Closed_As_Won_Lost_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Closed_Won_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Complete_Won_Lost_Analysis_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Confidential_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Create_Solution_Opportunity_Approval_Review_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Create_Solution_Opportunity_Approval_Review_Lite_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Submit_Customer_Support_Information_Form_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Customer_Engagement_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Customer_Payment_Communicated_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Deal_Registration_Status_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Detailed_Won_Lost_Reason_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Disable_Auto_Synchronization_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Distributor_On_Behalf_Of_Reseller_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Contract_Exist_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Finance_Method_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Forecast_Category_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Fulfillment_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Funding_Status_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Begin_Won_Lost_Analysis_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Add_Deployment_Schedule_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Installation_Completed_Date_Entered_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Installation_Management_Coordinate_Operator_Training_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Activity_Logged_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Log_Additional_Activities_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Opportunity_Assessment_Approval_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Obtain_Approval_From_Sales_Operations_Finance_Services_Manager_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Send_Signed_Contract_or_Purchase_Order_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Synchronized_with_Deal_Analysis_Response_Tool_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Updated_Primary_Incumbent_and_Winning_Competitor_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Updated_Estimated_Close_Date_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Updated_Estimated_Close_Date_1_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Updated_Products_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Updated_Products_1_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Updated_Sales_Team_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_HIPAA_Compliance_Required_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_HP_Financial_Services_Engaged_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_HP_Financial_Services_Engagement_Type_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Installation_Stage_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Order_Exist_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Order_Confirmed_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Training_Not_Needed_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Likelihood_Will_Revenue_Recognize_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Managed_By_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Services_Deal_Type_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Multiple_Country_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Multiple_Country_Type_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Order_Status_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Payment_Terms_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Pipeline_Exclusion_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Portal_Keep_Opportunity_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Send_Notification_Email_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Premier_Type_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Product_Condition_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Renewal_Type_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Requested_Quote_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Risk_Indicator_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Route_To_Market_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Automatic_Synchronization_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Site_Survey_Status_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Sales_Stage_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Trade_Agreements_Act_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Type_Name] NVARCHAR (350) NULL,
    [CRM_Opportunity_Unassigned_Opportunity_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Identify_Competitor_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Identify_Customer_Contact_Flag] NVARCHAR (20) NULL,
    [CRM_Opportunity_Status_Name] NVARCHAR (50) NULL,
    [CRM_Opportunity_Won_Flag] CHAR (1) NULL,
    [CRM_Opportunity_Commit_Flag] CHAR (1) NULL,
    [CRM_Opportunity_Pipeline_Flag] CHAR (1) NULL,
    [CRM_Opportunity_Upside_Flag] CHAR (1) NULL,
    [CRM_Opportunity_Open_Pipeline_Flag] CHAR (1) NULL,
    [CRM_Opportunity_Lost_Flag] CHAR (1) NULL,
    [CRM_Opportunity_Not_Pursuant_Flag] CHAR (1) NULL,
    [CRM_Opportunity_Error_Flag] CHAR (1) NULL,
    [CRM_Opportunity_Open_Flag] CHAR (1) NULL,
    [CRM_Opportunity_No_incumbent_Flag] CHAR (1) NULL,
    [CRM_Opportunity_Unscheduled_Flag] CHAR (1) NULL,
    [CRM_Opportunity_Early_Sales_Stage_Flag] CHAR (1) NULL,
    [CRM_Opportunity_Overdue_Flag] CHAR (1) NULL,
    [CRM_Opportunity_Stagnate_Sales_Stage_Flag] CHAR (1) NULL,
    [CRM_Opportunity_No_Update_Last_7_Days_Flag] CHAR (1) NULL,
    [CRM_Opportunity_No_Update_Last_90_Days_Flag] CHAR (1) NULL,
    [CRM_Opportunity_No_Product_Line_Flag] CHAR (1) NULL,
    [CRM_Opportunity_Sales_Stage1_Days_Count] INT NULL,
    [CRM_Opportunity_Sales_Stage2_Days_Count] INT NULL,
    [CRM_Opportunity_Sales_Stage3_Days_Count] INT NULL,
    [CRM_Opportunity_Sales_Stage4A_Days_Count] INT NULL,
    [CRM_Opportunity_Sales_Stage4B_Days_Count] INT NULL,
    [CRM_Opportunity_Sales_Stage5_Days_Count] INT NULL,
    [CRM_Opportunity_Sales_Stage6_Days_Count] INT NULL,
    [CRM_Opportunity_Account_Other_Party_Site_Instance_Id] INT NULL,
    [CRM_Opportunity_Account_Business_Relationship_Id] INT NULL,
    [CRM_Opportunity_Account_Business_Relationship_Item_Sequence_Number] INT NULL,
    [CRM_Opportunity_Account_Organization_Id] INT NULL,
    [CRM_Opportunity_Account_Country_Code] CHAR (3) NULL,
    [CRM_Opportunity_Primary_Partner_Organization_Id] INT NULL,
    [CRM_Opportunity_Reseller_Organization_Id] INT NULL,
    [CRM_Opportunity_Partner_Account_Organization_Id] INT NULL,
    [CRM_Opportunity_Partner_Organization_Id] INT NULL,
    [CRM_Opportunity_Currency_Currency_Code] NVARCHAR (5) NULL,
    [CRM_Opportunity_Primary_Competitor_Valid_Business_Group_GUID_Text] NVARCHAR (3999) NULL,
    [CRM_Opportunity_Primary_Competitor_Valid_Region_GUID_Text] NVARCHAR (3999) NULL,
    [CRM_Opportunity_Primary_Competitor_Winning_Competitor_Flag] NVARCHAR (10) NULL,
    [CRM_Opportunity_Owning_Business_Unit_Name] NVARCHAR (160) NULL,
    [Opportunity_Account_Country_Name] NVARCHAR (50) NULL,
    [Opportunity_Account_Region_Name] NVARCHAR (40) NULL,
    [Opportunity_Account_Subregion_1_Name] NVARCHAR (40) NULL,
    [Opportunity_Account_Subregion_2_Name] NVARCHAR (40) NULL,
    [Opportunity_Account_Subregion_3_Name] NVARCHAR (40) NULL,
    [Opportunity_Potential_Customer_Organization_Id] VARCHAR (21) NULL,
    [CRM_Opportunity_Sales_Stage_Name_Change_Count] INT NOT NULL,
    [CRM_Opportunity_Total_Opportunity_Value_Local_Amount_Change_Count] INT NOT NULL,
    [CRM_Opportunity_Close_Date_Change_Count] INT NOT NULL,
    [CRM_Opportunity_Rejection_Reason_Code] INT NULL,
    [CRM_Opportunity_Customer_Feedback_On_Benchmark_Code] INT NULL,
    [CRM_Opportunity_Demo_Request_Code] INT NULL,
    [CRM_Opportunity_Sales_Motion_Code] INT NULL,
    [CRM_Opportunity_Segment_Code] INT NULL,
    [CRM_Opportunity_Application_Type_Code] INT NULL,
    [CRM_Opportunity_Main_Material_Code] INT NULL,
    [CRM_Opportunity_Outsource_Spending_Code] INT NULL,
    [CRM_Opportunity_Main_Application_Code] INT NULL,
    [CRM_Opportunity_Subsegment_Code] INT NULL,
    [CRM_Opportunity_Benchmark_Shared_With_Customer_Code] INT NULL,
    [CRM_Opportunity_Application_Validated_By_Application_Engineer_Code] BIT NULL,
    [CRM_Opportunity_Financing_Secured_Code] BIT NULL,
    [CRM_Opportunity_Contract_Signed_Code] BIT NULL,
    [CRM_Opportunity_Approvals_Obtained_Code] BIT NULL,
    [CRM_Opportunity_Total_Cost_of_Ownership_Request_Code] BIT NULL,
    [CRM_Opportunity_Final_Quote_Code] BIT NULL,
    [CRM_Opportunity_Sellout_Code] BIT NULL,
    [CRM_Opportunity_Purchase_Order_Placed_At_Reseller_Code] BIT NULL,
    [CRM_Opportunity_Site_Readiness_Code] BIT NULL,
    [CRM_Opportunity_Primary_Partner_Site_Unique_Id] VARCHAR (36) NULL,
    [CRM_Opportunity_Primary_Partner_Site_Entity_Type_Name] NVARCHAR (50) NULL,
    [CRM_Opportunity_Please_Specify_Main_Application_Description] NVARCHAR (100) NULL,
    [CRM_Opportunity_Please_Specify_Target_Subsegment_Description] NVARCHAR (100) NULL,
    [CRM_Opportunity_Additional_Subsegment_Information_Description] NVARCHAR (100) NULL,
    [CRM_Opportunity_Shipment_Date] DATETIME NULL,
    [CRM_Opportunity_Application_Description] NVARCHAR (100) NULL,
    [CRM_Opportunity_Age_Number] INT NULL,
    [CRM_Opportunity_Current_Stage_Day_Number] INT NULL
)
    WITH (
    DATA_SOURCE = [crmalesADWDS]
    );

